### ISSUE TITLE
dbml2dot not compatable with python version < 3.7

### ISSUE THREAD

**Issue by hossam-houssien** [aviallon/dbml2dot#1]
> python -V
Python 3.6.2 :: Anaconda custom (64-bit)

> python -m dbml2dot -h
Traceback (most recent call last):
  File "..\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "..\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "..\Continuum\anaconda3\lib\site-packages\dbml2dot\__main__.py", line 1, in <module>
    import pydbml.classes
  File "..\Continuum\anaconda3\lib\site-packages\pydbml\__init__.py", line 1, in <module>
    from pydbml.parser import PyDBML, PyDBMLParseResults
  File "..\Continuum\anaconda3\lib\site-packages\pydbml\parser.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

found this link https://stackoverflow.com/questions/52889746/cant-import-annotations-from-future/52890129
it stated that:-
the error happens because according to PEP-563 the import of __future__ annotations is available starting with Python 3.7.

**Comment by aviallon** [comment]
I will look into it, although it looks like the issue comes from pydbml, not from dbml2dot itself.

**Comment by aviallon** [comment]
In any case, I use a lot of Python 3.7 features like f-strings, and finally, Python 3.6 security support is ending at the end of this year...
I really think the best option here is simply to upgrade to Python 3.7 or upwards (though that may be difficult sometimes).
